name: Build LaTeX Documents

on:
  pull_request:
    paths:
      - '**.tex'  # 只在 .tex 文件变更时触发

permissions:
  contents: read
  pull-requests: write  # 允许在 PR 中写入评论
  issues: write        # 允许在 issues 中写入评论

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "**/*.tex"  # 编译所有 .tex 文件
          latexmk_use_xelatex: true  
          work_in_root_file_dir: true

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "**/*.pdf"

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // 从 github.context 获取必要的上下文信息
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            
            // 递归查找所有 PDF 文件
            function findPDFs(dir) {
              let results = [];
              const files = fs.readdirSync(dir);
              
              for (const file of files) {
                const filePath = path.join(dir, file);
                const stat = fs.statSync(filePath);
                
                if (stat.isDirectory()) {
                  results = results.concat(findPDFs(filePath));
                } else if (file.endsWith('.pdf')) {
                  results.push(filePath);
                }
              }
              
              return results;
            }
            
            // 获取所有已编译的 PDF 文件路径
            const pdfs = findPDFs('.');
            
            let comment = '### LaTeX 编译结果\n\n';
            if (pdfs.length > 0) {
              comment += '✅ PDF 文件已成功生成。\n';
              comment += '找到的 PDF 文件：\n';
              pdfs.forEach(pdf => {
                comment += `- ${pdf}\n`;
              });
              comment += '\n你可以在 Actions 标签页下载编译后的 PDF 文件。\n';
            } else {
              comment += '❌ 未找到生成的 PDF 文件。\n';
              comment += '可能的原因：\n';
              comment += '1. LaTeX 编译失败\n';
              comment += '2. PDF 文件未在预期位置生成\n';
              comment += '请检查编译日志获取详细信息。\n';
            }
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });

      - name: List directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R 